language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
stages:
  - test
  - build
  - deploy
before_install:
  - make install
jobs:
  include:
    - stage: test
      script:
        - make fmt
        - make vet
        - make test
    - stage: build
      script:
        - make linux
        - make darwin
        - make windows
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: '${GITHUB_TOKEN}'
        file:
          - 'build/k8s-login-darwin-amd64'
          - 'build/k8s-login-linux-amd64'
          - 'build/k8s-login-windows-amd64.exe'
        skip_cleanup: true
        on:
          tags: true
